### PR TITLE
node-zwave-js-ui: add new package (WIP)

### PR DESCRIPTION
**Pull request by dwmw2**
I don't understand how the dependencies are supposed to work here. The resulting package seems to include a whole bunch of things which were already packaged, and surely we shouldn't ship a separate copy of them?

If I get that working, perhaps some things like vue ought to be split out into a separate package too?

### CODE REVIEW

**Comment by dwmw2** [comment]
The Domoticz package in OpenWrt uses libopenzwave but newer versions have switched to using zwave-js-ui, so I need to get that building. I'd really appreciate any help, as I'm not sure what I'm doing with node packaging — thanks!

**Comment by dwmw2** [comment]
I definitely don't understand how the dependencies are supposed to work...
```
root@U7623:/usr/lib/node/zwave-js-ui# node server/bin/www.js 
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '@zwave-js/core'
Require stack:
- /usr/lib/node/zwave-js-ui/server/lib/ZwaveClient.js
- /usr/lib/node/zwave-js-ui/server/config/store.js
- /usr/lib/node/zwave-js-ui/server/bin/www.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/usr/lib/node/zwave-js-ui/server/lib/ZwaveClient.js:31:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node/zwave-js-ui/server/lib/ZwaveClient.js',
    '/usr/lib/node/zwave-js-ui/server/config/store.js',
    '/usr/lib/node/zwave-js-ui/server/bin/www.js'
  ]
}

Node.js v20.10.0

```

But `/usr/lib/node/zwave-js/node_modules/@zwave-js/core` is there. How do I make it use that one?

**Comment by nxhack** [comment]
Hi @dwmw2 

Sorry for the delay in responding.
/* I was working on upgrading to FreeBSD 14.0 and couldn't find the time. ;) */

In order to separate the node module that require binary build, I split them into two.

https://github.com/nxhack/openwrt-node-packages/tree/zwave-js-ui/node-zwave-js-ui
https://github.com/nxhack/openwrt-node-packages/tree/zwave-js-ui/node-zwave-server

For module errors,I responded by adding to NODE_PATH.
https://github.com/nxhack/openwrt-node-packages/blob/zwave-js-ui/node-zwave-js-ui/files/zwave-js-ui.init#L9

The service started, but I couldn't figure out the configuration, so I added HOST=0.0.0.0, but could not connect to the Web UI.

Please follow up.

**Comment by dwmw2** [comment]
TIL... https://nodejs.medium.com/source-maps-in-node-js-482872b56116

So... is the version in standalone/ the version that *actually* gets run, having been translated from the original source code to pure JavaScript? Does that mean it's the *only* version we actually need to ship in the OpenWrt package? And can we drop the .map files because those are only useful for debugging? 

(Ideally the ecosystem would be mature enough that you can keep those separately, like we do debug files with gdb)

**Comment by nxhack** [comment]
I would like to know the conditions under which it works in order to reduce the capacity in a trickle. I am using apple homekit because I don't know this package.

**Comment by dwmw2** [comment]
Hm, my *image* builds are failing now because node packages which are set to `=m` (e.g. `CONFIG_PACKAGE_node-typescript=m` are ending up in the root filesystem as if they were built-in.
```
$ du -s staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-mediatek/usr/lib/node/* | sort -n
96	staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-mediatek/usr/lib/node/bufferutil
104	staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-mediatek/usr/lib/node/utf-8-validate
120	staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-mediatek/usr/lib/node/jsonfile
180	staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-mediatek/usr/lib/node/ws
192	staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-mediatek/usr/lib/node/arduino-firmata
436	staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-mediatek/usr/lib/node/serialport
2844	staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-mediatek/usr/lib/node/ts-node
3264	staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-mediatek/usr/lib/node/socket.io-client
3620	staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-mediatek/usr/lib/node/@serialport
4064	staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-mediatek/usr/lib/node/express
6224	staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-mediatek/usr/lib/node/mocha
7312	staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-mediatek/usr/lib/node/socket.io
14732	staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-mediatek/usr/lib/node/mqtt
39992	staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-mediatek/usr/lib/node/typescript
```

**Comment by nxhack** [comment]
I am working on size reduction, but as you pointed out, there are duplicates of express, etc.

As a test, I will create a monocilic "zwave-js-ui" package in a way that does not use existing packages.

**Comment by nxhack** [comment]
Monolithic Version

https://github.com/nxhack/openwrt-node-packages/tree/zwave-js-ui/node-zwave-js-ui

```
-rw-r--r-- 1 nxhack nxhack 21644893 Nov 29 12:28 node-zwave-js-ui_9.4.1-1_aarch64_generic.ipk
```

**Comment by dwmw2** [comment]
We probably want something like https://github.com/openwrt/packages/blob/master/utils/domoticz/files/domoticz.hotplug for naming the serial port. Although I wonder if that should be made generic, rather than different packages having variants of it.

**Comment by nxhack** [comment]
The software is working, but I cannot get a USB stick to test it. Z-Wave products are difficult to get in my country, Japan. I am looking for a product with the frequency approved by the Japanese local radio law (922 MHz), but it is difficult to purchase.

**Comment by dwmw2** [comment]
Yep, it's working here. Thanks. I'll try to make sense of all the files it puts in /etc/zwave-js-ui and work out which of them need to be in non-volatile vs. volatile storage, and which need to be kept on sysupgrade.

It would great to have a luci module which can build the `settings.json` config, but that can wait.

The main issue is that the virtual size of the program when it's running is 180MiB. It's also very slow to start up. Is it possible to compile either to bytecode or even to native code?

**Comment by nxhack** [comment]
For Reference
https://devcenter.heroku.com/articles/node-best-practices#avoid-garbage

**Comment by dwmw2** [comment]
Here's my attempt at incorporating the changes from https://github.com/zwave-js/zwave-js-ui/pull/3480

Fails with
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: zwave-js-ui@9.5.1
npm ERR! Found: zwave-js@undefined
npm ERR! node_modules/zwave-js
npm ERR!   zwave-js@"^12.4.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer zwave-js@"^12.2.1" from @zwave-js/server@1.33.0
npm ERR! node_modules/@zwave-js/server
npm ERR!   @zwave-js/server@"^1.33.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```
But then again, building current master fails that way too without my changes.

**Comment by nxhack** [comment]
Thanks for the information.
I will test it when it is merged upstream.

My stance is that I prefer to choose the right hardware to run node.js.
Primary memory is 2GB if possible; I need at least 1GB.
If storage is not enough, I choose to use microSD or USB storage to expand.

I don't like to compress source code because it is not readable. ;)

**Comment by dwmw2** [comment]
It's merged upstream in commit https://github.com/zwave-js/zwave-js-ui/commit/68326d635917895520be883013934d2789998d83

I appreciate that running on the right hardware is useful, but it's still useful to keep a bit of a handle on the size. With these changes we've gone from 100MiB to 30MiB on the file system, and even reduced the memory usage from 200MiB to 175MiB. If we allow things to blow up in size *too* much, we end up not really supporting the class of hardware that OpenWrt targets at all. And for ZWave in particular, that's a big regression because this used to be supported by a fairly minimal C++ library which was *tiny*. 

I also like source code to be readable, but I also don't necessarily want to have to install that readable source code on all the embedded devices that keep my network and my home functioning. I prefer to compile it and let them run that :)

**Comment by dwmw2** [comment]
Ah, my dependency problem mentioned in https://github.com/nxhack/openwrt-node-packages/pull/1826#issuecomment-1853086056 goes away if I remove my persistent npm cache (`rm -rf npm-cache/npm-cache-zwave-js-ui`)

**Comment by nxhack** [comment]
https://github.com/nxhack/openwrt-node-packages/tree/master/node-zwave-js-ui-bundle

Bundled version. I checked the working.

```
-rw-r--r-- 1 nxhack nxhack  4199778 Dec 14 16:09 node-zwave-js-ui-bundle_9.5.1-1_aarch64_generic.ipk
-rw-r--r-- 1 nxhack nxhack 15607129 Dec 13 12:11 node-zwave-js-ui_9.5.1-3_aarch64_generic.ipk
```

**Comment by nxhack** [comment]
This case is closed.
